services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: sherlock-kafka
    ports:
      - "9092:9092"
    mem_limit: 512m
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "_waEPl1uRDW3niG7t6m0dQ"
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    networks:
      - sherlock-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: sherlock-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: sherlock
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - sherlock-net

networks:
  sherlock-net:
    driver: bridge